kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: jenkins-local-storage-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-local-pv
spec:
  capacity:
    storage: 4Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: jenkins-local-storage
  local:
    path: /var/jenkins-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node1
          operator: In
          values:
          - local-storage
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-claim
  namespace: jenkins
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: jenkins-local-storage
  resources:
    requests:
      storage: 4Gi
